---
jobs:
  - name: do-tag
    plan:
      - in_parallel:
          - get: src
            trigger: true
          - put: version
            params:
              bump: patch
          - get: image
      - task: do
        image: image
        config:
          platform: linux
          inputs:
            - name: src
            - name: version
          run:
            path: sh
            args:
              - -euo
              - pipefail
              - -c
              - |
                echo "here is the src:"
                ls src
                echo "here is the version:"
                cat version/version
      - put: src
        params:
          repository: src
          tag: version/version
          rebase: true
          force: true

resources:
  - name: src
    type: git
    icon: github
    source:
      uri: https://github.com/mamachanko/git-resource-experiment
      branch: main
      username: token
      password: ((github.token))
      fetch_tags: true

  - name: version
    type: semver
    source:
      driver: git
      uri: https://github.com/mamachanko/git-resource-experiment
      branch: version
      username: token
      password: ((github.token))
      file: version

  - name: image
    type: registry-image
    icon: docker
    source:
      repository: busybox
      tag: latest
      username: ((dockerhub.username))
      password: ((dockerhub.password))

